### ISSUE TITLE
Compare.py

### ISSUE THREAD

**Issue by wsmorgan** [rosenbrockc/fortpy#27]
When attempting to run compare.py the following error occurs:
Traceback (most recent call last):
  File "/Users/wileymorgan/.virtualenvs/fortpy/bin/compare.py", line 36, in <module>
    initialize()
  File "/Users/wileymorgan/.virtualenvs/fortpy/bin/compare.py", line 13, in initialize
    args["xmltemplate"] = "{}.xml".format(source.split("/")[-1])
NameError: global name 'source' is not defined

**Comment by rosenbrockc** [comment]
Solved in Revision 1.5.5
