### ISSUE TITLE
ZeroDivisionError: float division by zero when comparing test outputs

### ISSUE THREAD

**Issue by wsmorgan** [rosenbrockc/fortpy#54]
Traceback (most recent call last):
  File "/Users/wileymorgan/.virtualenvs/fortpy/bin/runtests.py", line 91, in <module>
    initialize()
  File "/Users/wileymorgan/.virtualenvs/fortpy/bin/runtests.py", line 51, in initialize
    print_result(idk, result[idk].percent, timestr, result[idk].common)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/testing/tester.py", line 302, in percent
    return float(total) / (len(self.cases) + self.failure_count)
ZeroDivisionError: float division by zero

**Comment by rosenbrockc** [comment]
The only way this can happen is if fortpy doesn't find any test cases to report on (probably an error in the test XML). I added a check for it so that if no cases are present it will return 0 percent success (and 0 for `common` property as well). Check present in revision 1.6.0.

We will need more context to deal with the underlying problem: why didn't the cases get recognized?
