### ISSUE TITLE
Target with name="./file_name.out" for comparing to a already output file fails.

### ISSUE THREAD

**Issue by wsmorgan** [rosenbrockc/fortpy#64]
```
Traceback (most recent call last):
  File "/Users/wileymorgan/.virtualenvs/fortpy/bin/runtests.py", line 91, in <module>
    initialize()
  File "/Users/wileymorgan/.virtualenvs/fortpy/bin/runtests.py", line 39, in initialize
    t.writeall(args["codedir"])
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/testing/tester.py", line 594, in writeall
    self.tgenerator.write(self._codefolder)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/testing/generator.py", line 83, in write
    self._write_module(module, codefolder)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/testing/generator.py", line 99, in _write_module
    self._write_executable(module, anexec, coderoot)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/testing/generator.py", line 199, in _write_executable
    self.xgenerator.write(testid, coderoot)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/testing/executable.py", line 139, in write
    lines.append(self.writer.lines(testid, coderoot))
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/testing/method.py", line 114, in lines
    self._code_vars(result, "  ", testid)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/testing/method.py", line 265, in _code_vars
    self.method.group.code(testid, "vars", lines, spacer)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/testing/elements.py", line 2712, in code
    self._codes[testid][section](lines, spacer)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/testing/elements.py", line 2392, in code_vars
    t.code(lines, self.variables, "vars", spacer)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/testing/elements.py", line 2075, in code
    self._process(variables, spacer)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/testing/elements.py", line 2112, in _process
    self._process_simple(variables, spacer)
  File "/Users/wileymorgan/.virtualenvs/fortpy/lib/python2.7/site-packages/fortpy/testing/elements.py", line 2190, in _process_simple
    "a <global> tag or regular=true parameter doc tag.")
ValueError: Output target var ./clusters.out has not been initialized with a <global> tag or regular=true parameter doc tag.
```

**Comment by rosenbrockc** [comment]
Fixed in Revision 1.7.2.
