### ISSUE TITLE
AttributeError: 'Subroutine' object has no attribute 'type_search'

### ISSUE THREAD

**Issue by wsmorgan** [rosenbrockc/fortpy#82]
The error is coming up because a subroutine is being checked for its types in exectubale.py on line 382:
```
                end = anexec.parent.type_search(ftype, key)
```

The bug appeared when trying to parse monte_carlo.f90's subroutine check_for_possible_spin_swap() which has multiple subroutines within it. The one throwing the error is undo_test_spin_change which has a variable occEqv of type t_list. It appears that the code is trying to locate the type t_list in check_for_possible_spin_swap before looking elsewhere but can't because it is a subroutine and not a module.

The full error path is:
```
Traceback (most recent call last):
  File "/Users/wileymorgan/.virtualenvs/fortpy-dev/bin/runtests.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/wileymorgan/codes/fortpy/fortpy/scripts/runtests.py", line 148, in <module>
    do_testing(args)
  File "/Users/wileymorgan/codes/fortpy/fortpy/scripts/runtests.py", line 45, in do_testing
    t.writeall(args["codedir"])
  File "/Users/wileymorgan/codes/fortpy/fortpy/testing/tester.py", line 557, in writeall
    self.parser.parse(filepath, True, True)
  File "/Users/wileymorgan/codes/fortpy/fortpy/code.py", line 290, in parse
    dependencies, recursive, greedy)
  File "/Users/wileymorgan/codes/fortpy/fortpy/code.py", line 154, in _parse_from_file
    pmodules = self.modulep.parse(string, self)
  File "/Users/wileymorgan/codes/fortpy/fortpy/parsers/module.py", line 128, in parse
    return self._parse_modules(string, parent)
  File "/Users/wileymorgan/codes/fortpy/fortpy/parsers/module.py", line 163, in _parse_modules
    module = self._process_module(name, contents, parent, rmodule)
  File "/Users/wileymorgan/codes/fortpy/fortpy/parsers/module.py", line 223, in _process_module
    self.xparser.parse(result)
  File "/Users/wileymorgan/codes/fortpy/fortpy/parsers/executable.py", line 132, in parse
    self.parse_block(module.refstring, module, module, 0)
  File "/Users/wileymorgan/codes/fortpy/fortpy/parsers/executable.py", line 153, in parse_block
    self.parse_block(x.contents, x, module, depth + 1)
  File "/Users/wileymorgan/codes/fortpy/fortpy/parsers/executable.py", line 147, in parse_block
    x = self._process_execs(anexec, parent, module)
  File "/Users/wileymorgan/codes/fortpy/fortpy/parsers/executable.py", line 231, in _process_execs
    self._process_dependencies(result, cleaned)
  File "/Users/wileymorgan/codes/fortpy/fortpy/parsers/executable.py", line 291, in _process_dependencies
    self._process_dependlist(dependent, anexec, isSubroutine, mode)
  File "/Users/wileymorgan/codes/fortpy/fortpy/parsers/executable.py", line 340, in _process_dependlist
    self._add_dependency(key, dependlist, i, isSubroutine, anexec)
  File "/Users/wileymorgan/codes/fortpy/fortpy/parsers/executable.py", line 382, in _add_dependency
    end = anexec.parent.type_search(ftype, key)
AttributeError: 'Subroutine' object has no attribute 'type_search'
```

**Comment by rosenbrockc** [comment]
Changed:

```python
end = anexec.parent.type_search(ftype, key)
end = anexec.module.type_search(ftype, key)
```

Will be available in the next revision, which might be a while because the code is in a state at the moment with a large feature add. You can hack your local version with this in the meanwhile.
